	private float restitution = 0.945f;
	float deltaRest = .001f;
	int numTests = 10;
	int maxBounces = 40;
	int numBounces = 0;
	int numTest = 0;
	private boolean negativeSign = false;
	int ticks = 0;
	int maxTicks = 10000;